### ISSUE TITLE
Stroke line cap misinterpretation

### ISSUE THREAD

**Issue by harounhajem** [bodymovin/bodymovin-to-avd#3]
Bodymoving is misinterpreting the stroke line caps and the line joins. When exporting vector shape animations to AVD. They all become round instead of the selected value in After Effects. 

![artboard 1](https://user-images.githubusercontent.com/17148955/33825705-d00c7420-de62-11e7-9506-2b9bef2d96a1.jpg)

**Comment by bodymovin** [comment]
all strokes should be working now

**Comment by harounhajem** [comment]
@bodymovin Thanks for the update and job well done. <3
