### ISSUE TITLE
Path not exported to AVD

### ISSUE THREAD

**Issue by StefanSTV** [bodymovin/bodymovin-to-avd#5]
Hello again.

So, i managed to do the thing that i wanted, but now i have another issue.
I have an .aep with 3 paths, ready to be imported to Android Studio.

When exporting to JSON and importing it in Lottie, the animation works with no flaws.
But when exporting to AVD, the app crashes when trying to load it.

I think this is because there are no paths in the AVD

The JSON, AVD and .aep are attached

Thanks in advance!
[Desktop.zip](https://github.com/bodymovin/bodymovin-to-avd/files/2072962/Desktop.zip)

**Comment by bodymovin** [comment]
Hi, unfortunately gradients are not supported because AFAIK, they are not supported on the avd format.

**Comment by StefanSTV** [comment]
Yes, you are correct. There are paths now in AVD, after removing gradients.

Thanks.

**Comment by wsxyeah** [comment]
@bodymovin Gradient in AVD has been supported since API 24, any plan for supporting to export gradient data?

This is an example with gradient inside AVD.

```xml
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:aapt="http://schemas.android.com/aapt"
    android:width="262dp"
    android:height="264dp"
    android:viewportWidth="262"
    android:viewportHeight="264">
  <path
      android:pathData="m44.698,97.984l77.922,0l24.078,-74.102l24.078,74.102l77.922,0l-63.04,45.797l24.08,74.102l-63.04,-45.798l-63.04,45.798l24.08,-74.102l-63.04,-45.797z"
      android:strokeAlpha="null"
      android:strokeWidth="1.5"
      android:strokeColor="#000">
    <aapt:attr name="android:fillColor">
      <gradient 
          android:startY="23.882004"
          android:startX="44.697998"
          android:endY="23.882004"
          android:endX="248.698"
          android:type="linear">
        <item android:offset="0" android:color="#FF00BF5F"/>
        <item android:offset="1" android:color="#FFFF40A0"/>
      </gradient>
    </aapt:attr>
  </path>
</vector>
```
